language: java

# This is essential lest the script is ignored and Travis just runs gradle.
install: true

script: ./.travis-build.sh

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

## Disable so that we are not notified of build failures in forks.
## Use Travis default: send mail to author and committer of breaking commit.
# notifications:
#   email:
#     - checker-framework-dev@googlegroups.com
