language: java

# This is essential lest the script is ignored and Travis just runs gradle.
install: true

script: ./.travis-build.sh

sudo: false

jdk:
#  - openjdk7
  - oraclejdk8


git:
  depth: 9
